### ISSUE TITLE
Missing Gunlover trait.

### ISSUE THREAD

**Issue by dracwyrm** [PCGen/pcgen#1877]
Hi,

I have used Hero Lab and there is a Gunlover trait:
> Category: Combat
> 
> You are an avid fan of the new firearms now spreading throughout Freeport and the continent, and you have practised with them extensively.
> 
> Benefit: You reduce the misfire range for any gun you wield by 1, to a minimum of 1. If you have a feat or class feature that uses grit, your maximum grit points amount is increased by 1.
> 
> Appears in: Freeport Player's Guide, Freeport: City of Adventure

I don't know how to add a custom trait that does this, if you don't want to add this to the main program, could someone help me write a homebrew file that would add this?

Thanks,
Jon

**Comment by LegacyKing** [comment]
PCGen policy is to include entire source books. Piece-meal inclusions
cause an uptick in "bug" reports for something "missing".

I did a quick look, and we do not have Freeport in our current
offerings, so you would need to request the source book.

Adding a trait is fairly easy. Getting numbers to change correctly is
the harder part. For this, I would suggest holding off until the Formula
Parser conversion has taken place. Then you will have control over every
numerical aspect in PCGen. As it stands, misfire values are "hard-coded"
and not easily altered.

If you want the trait with just the text, then copy an exist combat
trait in the files, and rename all the named parts, and correct the
text, and you'd be good to go.

Gunlover
    KEY:Trait ~ Gunlover
    CATEGORY:Special Ability
    TYPE:Trait.BasicTrait.CombatTrait
    PREMULT:1,[PREABILITY:1,CATEGORY=Special Ability,Trait ~
Gunlover],[PREVAREQ:BypassTraitRestriction,1],[!PREABILITY:1,CATEGORY=Special
Ability,TYPE.CombatTrait]
    DESC:You are an avid fan of the new firearms now spreading
throughout Freeport and the continent, and you have practised with them
extensively. Benefit: You reduce the misfire range for any gun you wield
by 1, to a minimum of 1. If you have a feat or class feature that uses
grit, your maximum grit points amount is increased by 1.
    SOURCEPAGE:p.
    BONUS:VAR|GritPoints|1

Also, PCGen uses JIRA to handle requests and bug reports -
pcgenorg.atlassian.net

Cheers,

**Comment by dracwyrm** [comment]
Thanks for the reply.
How would I request Freeport?
Would the Formula Parser allow adjusting the Misfires?

Cheers,
Jon

**Comment by LegacyKing** [comment]
NewSource Request on the Jira link I gave you.

Yes, the new Formula Parser would control ALL numbers. The existing JEP
system only deals with Global and barely touches Weapons, which are
Local objects. The new Formula System categorizes numbers by either
Global, Local, or Part (of a Local).

For a Part example, we have Equipment - A Local Object, but a
Double-Headed Weapon can have completely different values, thus we have
EQUIPMENT.PART to handle this group.

A Misfire value would be a Local.Part since you could have a
Rifle-Staff. The existing JEP system cannot easily handle this, which is
why we are heading towards a Complete replacement.

You can play with the new system, as it's implemented, just a few bugs
to work out before we begin the process of conversion. I've been told
that the fixes are estimated to be in by Thanksgiving. Hit me up direct
for more details - Help@pcgen.org

Cheers,
