### ISSUE TITLE
Debian stable comes with Java 7

### ISSUE THREAD

**Issue by ksingvo** [PCGen/pcgen#2906]
When running pcgen 6.07.02 using Debian stable (= jessie, v8.8), I notice this failure:

Exception in thread "main" java.lang.UnsupportedClassVersionError: pcgen/system/Main : Unsupported major.minor version 52.0
....

52.0 seems to be Java 8, but the Java version ootb for Debian (Linux) stable is only Java 7.

Is Java 8 really necessary, or can the demands be lowered?

Thanks in advance.

Best regards,
Klaus.

**Comment by LegacyKing** [comment]
Hi @ksingvo aka Klaus, Yes, Java 8 is required. To give history here. The 6.08/7.00 release is building to remake the GUI from Java Swing to Java FX to address the High Resolution Display problems everyone has currently. In order to migrate to Java FX, it was required we migrate to the Java 8 library. We have the Java 8 changes in place (Java 7 or earlier will barf with PCGen development now). Next is to move forward to the Java FX rebuild. It should be possible to get Java 8 on Debian. We don't make these changes without fairly good reasons. 

Cheers,
Andrew

**Comment by ksingvo** [comment]
Hi Andrew,
thanks for your helpful explanation.
Hopefully the upgrade of Debian Stable (from v8 to v9) will bring Java 8 and FX support along.

Please change the release notes accordingly. They still say:
"PCGen has been tested with both Java 7 (including OpenJDK) and Java 8."

Best regards,
Klaus.
