### ISSUE TITLE
"Ability Focus" feat can't be applied to "Throw Splash Weapon" special attack

### ISSUE THREAD

**Issue by Farawen** [PCGen/pcgen#4063]
## Context:

* *Ability Focus* is a feat from *Pathfinder Game Bestiary* (`paizo/roleplaying_game/core_essentials/ce_feats.lst`, line 8).
* Feat pre-requisite is *"Special attack"* .
* From alchemist's bombs description: *"Thrown bombs [...] use the Throw Splash Weapon special attack"*.

According to forums, some DM allow use of Ability Focus for PC, some don't (mine does).

## Expected / reproduce:

An alchemist should be qualified for the feat *Ability Focus* with *Throw Splash Weapon* .

## What I get with pcgen 6.07.08:

Alchemist is unqualified for *Ability Focus*. `Requirements: all of ( at least 1 TYPE.Ability Focus Ability Focus )` (I don't understand the requirement)

## (im)possible workaround:

I've tried allowing feat without prerequisites (`Preference->Houserules->FEATPRE`), but feat still can't be taken.

Once again, thanks for the work, folks!

**Comment by LegacyKing** [comment]
So, what you really want is Ability Focus "Bomb", cause that's the only thing with a DC in the program.  Otherwise you're asking me to code up something that has nothing to impact. Splash Weapons don't have DCs according the Paizo below...

**Throw Anything (Ex):** _All alchemists gain the Throw Anything feat as a bonus feat at 1st level. An alchemist adds his Intelligence modifier to damage done with splash weapons, including the splash damage if any. This bonus damage is already included in the bomb class feature._

**Throw Anything (Combat)**
_You are used to throwing things you have on hand.

Benefit: You do not suffer any penalties for using an improvised ranged weapon. You receive a +1 circumstance bonus on attack rolls made with thrown splash weapons.

Normal: You take a –4 penalty on attack rolls made with an improvised weapon._

And the icing on the cake:
**Throw Splash Weapon**
_A splash weapon is a ranged weapon that breaks on impact, splashing or scattering its contents over its target and nearby creatures or objects. To attack with a splash weapon, make a ranged touch attack against the target. Thrown splash weapons require no weapon proficiency, so you don't take the –4 nonproficiency penalty. A hit deals direct hit damage to the target, and splash damage to all creatures within 5 feet of the target. If the target is Large or larger, you choose one of its squares and the splash damage affects creatures within 5 feet of that square. Splash weapons cannot deal precision-based damage (such as sneak attack).

You can instead target a specific grid intersection. Treat this as a ranged attack against AC 5. However, if you target a grid intersection, creatures in all adjacent squares are dealt the splash damage, and the direct hit damage is not dealt to any creature. You can't target a grid intersection occupied by a creature, such as a Large or larger creature; in this case, you're aiming at the creature.

If you miss the target (whether aiming at a creature or a grid intersection), roll 1d8. This determines the misdirection of the throw, with 1 falling short (off-target in a straight line toward the thrower), and 2 through 8 rotating around the target creature or grid intersection in a clockwise direction. Then, count a number of squares in the indicated direction equal to the range increment of the throw. After you determine where the weapon landed, it deals splash damage to all creatures in that square and in all adjacent squares._
--
From Bomb:  Splash damage from an alchemist bomb is always equal to the bomb's minimum damage (so if the bomb would deal 2d6+4 points of fire damage on a direct hit, its splash damage would be 6 points of fire damage). **Those caught in the splash damage can attempt a Reflex save for half damage. The DC of this save is equal to 10 + 1/2 the alchemist's level + the alchemist's Intelligence modifier.**

**Comment by Farawen** [comment]
Ok, I get it. Yes, the bonus was intended for the bombs, not the special attack itself.

Thanks for the quick answer.
