### ISSUE TITLE
Wizard 'Heighten Spell' feat should be able to raise a spell more than one level

### ISSUE THREAD

**Issue by alecschule** [PCGen/pcgen#6098]
I'm using a recently compiled version of PCGen, (6.09.02-DEV) and it seems that the 'heighten spell' feat can only be used to raise a spell one level.

I found this issue describing the same problem, and the response was that it was already fixed: https://pcgenorg.atlassian.net/browse/DATA-3886. Still, I really don't see any way to use the heighten spell feat to prepare fireball as a 5th level spell. (for example)

Please let me know if there's any other information I can provide to help. Thank you.

**Comment by LegacyKing** [comment]
Not sure what the request is. You can use a higher level slot, but the Heighten Spell only adds 1 level.

**Comment by TwistedFaith84** [comment]
My guess is that @alecschule wants to take sometime like fireball from its 3rrd level to something higher like a 5th or 6th level (with all the goodness off Higher DCs, Damage, ect..) which is what Heighten Spell is supposed to be able to do. And as it stands PCGen will only Heighten it by 1 level instead of however high the caster wants it (max ~9th).

**Comment by LegacyKing** [comment]
So we want Heighten Spell +x?  Okay, I will look into it.

**Comment by LegacyKing** [comment]
[cr_feats.zip](https://github.com/PCGen/pcgen/files/4001370/cr_feats.zip)
Here you go
