### ISSUE TITLE
Logs remains blank despite failed loads[BUG] 

### ISSUE THREAD

**Issue by Runner-L** [PCGen/pcgen#6523]
**I can not seem to run PCGen with BahamutDragon's 3rd party content**
I have been trying by adding source books little by little but PcGen keeps erroring out whenever I try to load his sourcebooks. I have tried to have the Logs open because the load keeps failing when ever loading gets to sa_kits.lst an error window pops up saying that campaigns failed to load however whether I click the red circle on the bottom or press f10  the debug log remains blank.

**To Reproduce**
1. Download and install 'PCGen 6.08.00RC8'
2. Download zip folder by BahamutDragon at 'https://github.com/BahamutDragon/pcgen'
3. Extract folder to desktop
4. Copy files into the correct folders
5. Launch Program and select Dungeons and Dragons - core books as the game type
6. Press CTRL+L then select advance tab
7. Click on 35e Bahamut's select all the sources applicable
8. Load sources, the error should no occur and the debug log should remain blank 

**Expected behavior**
A successful execution of PCGen with all 3rd party content displaying.

**Desktop**
 - Windows 10 Pro
 - Chrome
 - Version 20H2

**Additional context**
I have also reached out to Bahamut Dragons Github Page as well to try and resolve the issue.

**Comment by LegacyKing** [comment]
Hi, as we don't maintain 3rd party sources, such as Bahamut's, it remains difficult for us to diagnose what the exact problem is. If I cannot readily reproduce the issue, then I cannot fix said issue. Needless to say, it sounds like the culprit is one of the sourcebooks being loaded from the 3rd party. Continue to work with them to resolve your issue. Good luck and happy gaming!
